apiVersion: v1
kind: Service
metadata:
  name: tomcat-service
  namespace: tomcat
spec:
  type: NodePort
  selector:
    app: tomcat
  ports:
  - name: http
    port: 80
    targetPort: 8080
    nodePort: 32080

