apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tomcat-eks
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/MaheshL9566/tomcat-eks-argocd-demo.git
    targetRevision: main
    path: k8s

  destination:
    server: https://kubernetes.default.svc
    namespace: tomcat

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

